on:
  push:

name: Release Builds
jobs:
  linux:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/flutter/flutter.git
          cd flutter
      - run: echo ::add-path::`pwd`"/flutter/bin"

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: actions/checkout@v2
        with:
          path: 'app'

      - run: |
          cd app
          flutter pub get
          flutter build apk --release

      - name: Create Android Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'app/build/app/outputs/apk/release/app-release.apk'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
